캐릭터 선택창, 도움말

f12 막기
별,차트 조회권환 확실히 하고 (로그인해도 사실 싸피인 아니여도 볼수있음) 방명록 403 처리하기
첨에 다뿌리고 시작하는데 그룹화제거 누르면 별 많다고 안뿌려줌

엔터를 두번 눌러야 채팅이 쳐집니다.
=> 엔터누르면 채팅창 켜짐 엔터 또 누르면 채팅 입력 ecs를 대체할 다른 버튼 누르면 채팅창 꺼지게?
로그인 안하고 login to play 누르고 확인 누르고 다시  login to play 누르면 무반응
"나는문어" 닉네임을 쓰다가 URL입력으로 https://ssafy-star.com/로 갔다가 다시 메타버스를 "나는문어"로 들어가려고 하면 중복닉네임으로 표시됨
시점 원래대로 버튼 있어야 할 듯

cp -r /unitydir/* /var/lib/docker/overlay2/ebc64f4f79cec81abf0171bcb0adf2423e616036a59d8a79dbbc3760f3c7d9e5/merged/usr/share/nginx/html/