app:
  oauth2:
    authorized-redirect-uris:
      - https://localhost:8080/oauth2/token
      - http://localhost:3000/oauth2/token

  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 86400000

mysql:
  port: localhost:3306
  user: root
  pwd: ssafy
#  user: STAR
#  pwd: "!star@ssafy-start#304"

redis:
  host: localhost
  port: 6379
  pwd: ssafystar304

oauth2:
  google:
    id: 210492167110-lfiuso34ko9chdv1qvkh39hefeh8gugv.apps.googleusercontent.com
    secret: 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
  naver:
    id: oIcX6isYx1rMy8rixb74
    secret: zFpNuVO8og
  kakao:
    id: cf2b28e65350426d2a63e8c5ff602bf1
    secret: SQN107LsmEwYtfKy38Fii0zVOysPacdw

cors:
  allowedOrigins: http://localhost:3000, http://localhost:8080
